version: '3.8'

services:
  post-service:
    build: .
    container_name: pulse-post-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/pulse_posts
      SPRING_DATASOURCE_USERNAME: pulse_user
      SPRING_DATASOURCE_PASSWORD: pulse_user
      USER_SERVICE_BASE_URL: http://host.docker.internal:8081
    ports:
      - "8082:8082"
    networks:
      - pulse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  pulse-network:
    external: true
