services:
  postgres-auth:
    image: postgres:15
    container_name: auth-service-db
    environment:
      POSTGRES_DB: pulse_auth
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse_user -d pulse_auth"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  postgres-tweets:
    image: postgres:15
    container_name: tweet-service-db
    environment:
      POSTGRES_DB: pulse_tweets
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_tweets_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse_user -d pulse_tweets"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/pulse_auth
      SPRING_DATASOURCE_USERNAME: pulse_user
      SPRING_DATASOURCE_PASSWORD: pulse_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: mySecretKey123456789012345678901234567890
      JWT_EXPIRATION: 86400000
    depends_on:
      postgres-auth:
        condition: service_healthy
    restart: unless-stopped

  tweet-service:
    build: ./tweet-service
    container_name: tweet-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-tweets:5432/pulse_tweets
      SPRING_DATASOURCE_USERNAME: pulse_user
      SPRING_DATASOURCE_PASSWORD: pulse_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: mySecretKey123456789012345678901234567890
      JWT_EXPIRATION: 86400000
    depends_on:
      postgres-tweets:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_auth_data:
  postgres_tweets_data:
