services:
  # User Service (Node.js)
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
      target: development
    container_name: pulse-user-service
    environment:
      NODE_ENV: development
      PORT: 8081
      DATABASE_URL: postgresql://pulse_user:pulse_user@host.docker.internal:5432/pulse_users
      JWT_SECRET: dev-secret-key-change-in-production
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 1000
      BCRYPT_ROUNDS: 10
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: debug
      ADMIN_EMAIL: admin@pulse.com
      ADMIN_PASSWORD: admin123
      GOOGLE_CLIENT_ID: 324113479892-7cq7ntoptj8cfn5u65ahssm5af55hdmd
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      GOOGLE_CALLBACK_URL: http://localhost:8081/api/v1/auth/google/callback
      SESSION_SECRET: dev-session-secret-change-in-production
      SESSION_MAX_AGE: 86400000
    ports:
      - "8081:8081"
    volumes:
      - ./user-service:/app
      - /app/node_modules
      - ./user-service/logs:/app/logs
    restart: unless-stopped
    networks:
      - pulse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Post Service (Java Spring Boot)
  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: pulse-post-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/pulse_posts
      SPRING_DATASOURCE_USERNAME: pulse_user
      SPRING_DATASOURCE_PASSWORD: pulse_user
      JWT_SECRET: dev-secret-key-change-in-production
      JWT_EXPIRATION: 86400000
      USER_SERVICE_BASE_URL: http://host.docker.internal:8081
      USER_SERVICE_TIMEOUT: 5000
      USER_SERVICE_RETRY_ATTEMPTS: 3
      CONTENT_MAX_POST_LENGTH: 2000
      CONTENT_MAX_COMMENT_LENGTH: 500
      CONTENT_MAX_IMAGE_SIZE_MB: 10
      CONTENT_MAX_VIDEO_SIZE_MB: 100
      CONTENT_ALLOWED_IMAGE_TYPES: jpg,jpeg,png,gif,webp
      CONTENT_ALLOWED_VIDEO_TYPES: mp4,webm,mov
      LOGGING_LEVEL_COM_PULSE_POST: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: WARN
    ports:
      - "8082:8082"
    depends_on:
      user-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pulse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  pulse-network:
    driver: bridge
