apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEV5TURZeApORFE1TkRsYUZ3MDBOVEV5TURZeE5EUTVORGxhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEaXpObFFhQVRKTThKN214TVFoeldrbS9FL2VCR3Q0d01jeVBhckVoNXRkRnBGL29ldgpLaUlsakR0RUl0YWRpUm80cFdiUUtMemZjV1gvNWdyUU5QdjU3S2NtU3hQVzBIZVFoUTFzRHUxczcvMi9vcW9ICi9HeG1WakxYNHlNcVRoVFRtM3dkUzYzRTVWSDEwWUZSRVZZTjRwc2dublFPeHNHRlJNU3NHbklVN1JMSHJya1QKSWk3ZHVJY2dyOFByZW11L2c4anNvMU1yTjRKelFidzRlQU1TdmkwSStqK3NqS3QwWFRlR1dKMk1OWVBBd29kUgp6NG8vZ2RBMDhBRmlVNHErMjhROW02UEJiZG1FUlNlV0Y2ZWJkZ3dBalV4dXozQngxT1Zna2tBQ1JVaG1GQ1hUCmZhTmIwckpLUlN1aVhoMS9yVzRLVnhDdEJnRDhhM0pjNzRhdEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRQZUtiVW9GQjNRbHMzdjAxQQpRMHlZMnB0ckp6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFkeWtlQTJ2T2g1V3RJbmgxSTFoU05qM2VDR3VGCm5WTlpQQ2swRnVVenMwRTZiek1rRmthS1FiT1VNNmJmUm5uVUZieWVya0s3bXBRNmFBdE1XRFpsNVlaMUROOTgKUlY0dThUaTZlWFhIZzJ2MmZRUEJrd0J5TEFobnVFOHg2ZlFuaHJjQnNNNi9aWHErZjlwMXlyRmhDcnE3VlZMRQpCSWFqd1JBUGNWQm93NU4ySGFUNDdCVElKeEhNSlhxOVJhRTUyUEF3QkZTaHZqN3dFMjNjUmxQYWQ4RU5uOU5JCm0yMmVhTWxJOWdIMnQybWgxRWFQckI3SFJrcnE5MllMWFB5Nm80NzV2TWttZFFFYTJ0cnorOXVyWmN0TVQvRlYKejlEbGszdU10ZnVkRzF5U3dIalg2QnFSMWROWGdsMHhlbG9lMVpaVjJBc2pQOWVDMHlMd0U4TVFoZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://c8863a29-3956-4828-a5ce-c0d173bf80ef.k8s.ondigitalocean.com
  name: do-ams3-pulse-cluster
contexts:
- context:
    cluster: do-ams3-pulse-cluster
    user: do-ams3-pulse-cluster-admin
  name: do-ams3-pulse-cluster
current-context: do-ams3-pulse-cluster
kind: Config
preferences: {}
users:
- name: do-ams3-pulse-cluster-admin
  user:
    token: YOUR_DIGITALOCEAN_TOKEN
