server:
  port: 8081

spring:
  application:
    name: tweet-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/pulse_tweets
    username: pulse_user
    password: pulse_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# JWT Configuration (should match auth-service)
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.pulse.tweet: DEBUG
    org.springframework.security: DEBUG

