server:
  port: 8082

spring:
  application:
    name: post-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/pulse_posts
    username: pulse_user
    password: pulse_user
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  cache:
    type: simple
    cache-names:
      - user-cache
      - post-cache

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# User Service Integration
user-service:
  base-url: http://localhost:8081
  timeout: 5000
  retry-attempts: 3

# Content Validation Configuration
content:
  max-post-length: 2000
  max-comment-length: 500
  max-image-size-mb: 10
  max-video-size-mb: 100
  allowed-image-types: jpg,jpeg,png,gif,webp
  allowed-video-types: mp4,webm,mov

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.pulse.post: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/post-service.log
