services:
  postgres:
    image: postgres:15-alpine
    container_name: pulse-users-db
    environment:
      POSTGRES_DB: pulse_users
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse_user -d pulse_users"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - pulse-network

  redis:
    image: redis:7-alpine
    container_name: pulse-users-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - pulse-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: pulse-user-service
    environment:
      NODE_ENV: development
      PORT: 8081
      DATABASE_URL: postgresql://pulse_user:pulse_password@postgres:5432/pulse_users
      JWT_SECRET: dev-secret-key-change-in-production
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 1000
      BCRYPT_ROUNDS: 10
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: debug
      ADMIN_EMAIL: admin@pulse.com
      ADMIN_PASSWORD: admin123
      SESSION_SECRET: dev-session-secret-change-in-production
      SESSION_MAX_AGE: 86400000
      REDIS_URL: redis://redis:6379
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - pulse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Post Service Database
  post-service-db:
    image: postgres:15-alpine
    container_name: pulse-posts-db
    environment:
      POSTGRES_DB: pulse_posts_service_db
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - post_service_data:/var/lib/postgresql/data
      - ../post-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse_user -d pulse_posts_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - pulse-network

  # Post Service
  post-service:
    build:
      context: ../post-service
      dockerfile: Dockerfile.simple
    container_name: pulse-post-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://post-service-db:5432/pulse_posts_service_db
      SPRING_DATASOURCE_USERNAME: pulse_user
      SPRING_DATASOURCE_PASSWORD: pulse_password
      JWT_SECRET: dev-secret-key-change-in-production
      JWT_EXPIRATION: 86400000
      USER_SERVICE_BASE_URL: http://user-service:8081
      USER_SERVICE_TIMEOUT: 5000
      USER_SERVICE_RETRY_ATTEMPTS: 3
      CONTENT_MAX_POST_LENGTH: 2000
      CONTENT_MAX_COMMENT_LENGTH: 500
      CONTENT_MAX_IMAGE_SIZE_MB: 10
      CONTENT_MAX_VIDEO_SIZE_MB: 100
      CONTENT_ALLOWED_IMAGE_TYPES: jpg,jpeg,png,gif,webp
      CONTENT_ALLOWED_VIDEO_TYPES: mp4,webm,mov
      LOGGING_LEVEL_COM_PULSE_POST: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: WARN
    ports:
      - "8082:8082"
    depends_on:
      post-service-db:
        condition: service_healthy
      user-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - pulse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  post_service_data:
    driver: local

networks:
  pulse-network:
    driver: bridge
    external: true
