version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pulse-users-db
    environment:
      POSTGRES_DB: pulse_users
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: pulse_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse_user -d pulse_users"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pulse-users-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  user-service:
    build: .
    container_name: pulse-user-service
    environment:
      NODE_ENV: development
      PORT: 8080
      DATABASE_URL: postgresql://pulse_user:pulse_password@postgres:5432/pulse_users
      JWT_SECRET: dev-secret-key
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 1000
      BCRYPT_ROUNDS: 10
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: debug
      ADMIN_EMAIL: admin@pulse.com
      ADMIN_PASSWORD: admin123
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      GOOGLE_CALLBACK_URL: http://localhost:8080/api/v1/auth/google/callback
      SESSION_SECRET: dev-session-secret
      SESSION_MAX_AGE: 86400000
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
